# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Express',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_name', models.CharField(max_length=100)),
                ('receive_phone', models.CharField(max_length=20)),
                ('receive_address', models.CharField(max_length=100)),
                ('receive_postcode', models.CharField(max_length=20)),
                ('goods', models.CharField(max_length=100)),
                ('express_company', models.CharField(max_length=20)),
                ('remarks', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=15)),
                ('send_name', models.CharField(max_length=100)),
                ('send_phone', models.CharField(max_length=20)),
                ('send_address', models.CharField(max_length=100)),
                ('send_postcode', models.CharField(max_length=20)),
                ('extra_price', models.CharField(max_length=20)),
            ],
        ),
    ]
