# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Express', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='express',
            name='pos',
            field=models.CharField(default=datetime.datetime(2016, 4, 26, 8, 54, 10, 559940, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
