# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Express', '0003_deliverman'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverman',
            name='express',
            field=models.ForeignKey(default='18161251991', on_delete=django.db.models.deletion.CASCADE, to='Express.Express'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliverman',
            name='deliverPhone',
            field=models.CharField(max_length=20),
        ),
    ]
