# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Express', '0004_auto_20160428_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverman',
            name='express',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Express.Express'),
        ),
    ]
