# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Express', '0005_auto_20160429_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifycode', models.CharField(max_length=10)),
                ('codestatus', models.BooleanField(default=False)),
                ('codedate', models.CharField(max_length=20)),
                ('express', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Express.Express')),
            ],
        ),
    ]
