# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Express', '0006_verifycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverman',
            name='deliverID',
            field=models.CharField(default='2013220102015', max_length=20),
            preserve_default=False,
        ),
    ]
