# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Express', '0007_deliverman_deliverid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthDeliver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverPhone', models.CharField(max_length=20)),
                ('deliverID', models.CharField(max_length=20)),
            ],
        ),
    ]
